config/routes.rb
Cookbook::Application.routes.draw do

  namespace :admin do
    
    root :to => "main#index"
    
    resources :categories    
    resources :dishes do
      member do
        get 'visibility'
      end
    end
        
  end
  
  root :to => "main#index"  
  match '/about', :to => 'main#about'
  

end

app/models/category.rb
class Category < ActiveRecord::Base	
  validates :name, :presence => true, :uniqueness => true
  
  has_many :dishes  
       
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :recipe, :presence => true
  
  belongs_to :category
   
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
	
  before_filter :get_category, :only => [:edit, :update, :destroy]
  before_filter :get_categories, :only => [:index]
  respond_to :html, :xml, :json
  helper_method :sort_column, :sort_direction

  def index  	
  	respond_with(@categories)  	
  end
  
  def new    
    respond_with(@category = Category.new )    
  end
  
  def edit 
  	respond_with(@category)  
  end

  def create
  	@category = Category.new(params[:category])
  	if @category.save
  	  flash[:notice] = "Successfully created category."
  	  redirect_to admin_categories_path
  	else
      render :action => 'new'
    end     		     
  end

  def update 	
    if @category.update_attributes(params[:category])
      flash[:notice] = "Successfully updated category."
      redirect_to admin_categories_path
    else    
      render :action => 'edit'
    end
  end 
    
  def destroy    
    @category.destroy    
    flash[:notice] = "Successfully destroyed category."    
    respond_with([:admin, @category])    
  end
  
  private 
    def get_category
      @category = Category.find(params[:id], :include => :dishes)
    end
    
    def get_categories      
      @categories = Category.order(sort_column + " " + sort_direction)
    end  
  
    def sort_column
      Category.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
      
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
       
end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < AdminController
		
  before_filter :get_dish, :only => [:show, :edit, :update, :destroy, :visibility]
  before_filter :get_dishes, :only => [:index, :visibility]
  before_filter :get_categories, :only => [:new, :edit, :update]
  respond_to :html, :xml, :json, :js
  helper_method :sort_column, :sort_direction

  def index
  	respond_with(@dishes)  	
  end
  
  def show
  	respond_with(@dish)   
  end

  def new  
    @dish = Dish.new :category_id => params[:category_id]    
    respond_with(@dish)    
  end
  
  def edit 
  	respond_with(@dish)  
  end

  def create
  	@dish = Dish.new(params[:dish])
  	if @dish.save  	 
  	  respond_with([:admin, @dish], :notice => "Successfully created dish.")
  	else
      render :action => 'new'
    end     		     
  end

  def update 	
    if @dish.update_attributes(params[:dish])
      flash[:notice] = "Successfully updated dish."  
    end
    respond_with([:admin, @dish])    
  end 
    
  def visibility    
    @dish.visible == true ? @dish.visible = false : @dish.visible = true
    @dish.update_attributes(params[:dish])
    
    # if @dish.update_attributes(params[:dish])
    #   flash[:notice] = "Successfully updated dish."                              
    # end
    respond_with([:admin, @dish])    
  end
  
  def destroy    
    @dish.destroy    
    flash[:notice] = "Successfully destroyed dish."
    respond_with([:admin, @dish])    
  end
  
  private 
    def get_dish
      @dish = Dish.find(params[:id])
    end
    
    def get_dishes
      @dishes = Dish.order(sort_column + " " + sort_direction) 
    end  
  
    def get_categories
      @categories = Category.order('name')
    end  
  
    def sort_column
      Dish.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
end

app/controllers/admin/main_controller.rb
class Admin::MainController < AdminController
  def index
    @title = "Index"
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < PublicController
  
  def index    
    @title="Home"
  end
  
  def about 
    @title="About"       
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  layout 'public'
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/dishes_helper.rb
module Admin::DishesHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/admin_helper.rb
module AdminHelper
         
  def sortable(column, title = nil)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}  
  end  	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
      
  def title
    base_title = "CookBook"
    @title.blank? ? base_title : "#{base_title} | #{@title}"    
  end
  
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/categories/_form.html.haml
- semantic_form_for [:admin, @category], :html => { :multipart => true } do |form|
  - form.inputs do
    = form.input :name  
    = form.buttons
     

app/views/admin/categories/edit.html.haml
%h2=t'Editing'

= render 'form'

= link_to (t'Back'), admin_categories_path

app/views/admin/categories/index.html.haml
%h2=t'Categories'
= link_to (t'New Category'), new_admin_category_path
%br
%br
- unless @categories.blank?
  %table
    %thead
      %tr.pretty        
        %th= sortable "id"
        %th= sortable "name", "#{t'activerecord.attributes.category.name'}"        
        %th= sortable "dishes", "#{t'activerecord.attributes.category.dishes'}"        
        %th=t'Operations'  
    %tbody    
      - @categories.each do |category|        
        %tr
          %td= category.id
          %td= category.name
          %td= category.dishes.count          
          %td        
            = link_to (t'Edit'), edit_admin_category_path(category)
            = link_to (t'Destroy'), [:admin, category], :confirm => "#{t'Are you sure?'}", :method => :delete
- else 
  %p=t'Oops, No Categories' 

= link_to (t'New Category'), new_admin_category_path       

app/views/admin/categories/new.html.haml
%h2=t'New Category'

= render 'form'
= link_to (t'Back'), admin_categories_path

app/views/admin/categories/show.html.haml
.show_categories  
  = render :partial => "/admin/shared/categories_list", :locals => { :categories => @categories }

.show_dishes
  %h2= @category.name  
  
  = render :partial => "/admin/shared/dishes_list", :locals => { :dishes => @dishes }

  %br= link_to (t'New Dish'), new_admin_dish_path(:category_id => @category.id)

app/views/admin/dishes/_form.html.haml
- semantic_form_for [:admin, @dish], :html => { :multipart => true } do |form|
  - form.inputs do
    = form.input :category, :collection => @categories
    = form.input :name    
    = form.input :recipe  
    
    = form.buttons
     

app/views/admin/dishes/edit.html.haml
%h2=t'Editing'

= render 'form'

= link_to (t'Show'), [:admin, @dish]
= link_to (t'Back'), admin_dishes_path

app/views/admin/dishes/index.html.haml
%h2=t'Dishes'
= link_to (t'New Dish'), new_admin_dish_path
%br
%br

= render :partial => "/admin/shared/dishes_list", :locals => { :dishes => @dishes }
 
= link_to (t'New Dish'), new_admin_dish_path
 

app/views/admin/dishes/new.html.haml
%h2=t'New Dish'

= render 'form'
= link_to (t'Back'), admin_dishes_path

app/views/admin/dishes/show.html.haml
- unless @dish.category.blank?
  = @dish.category.name
  &#047
- else       
  .lack=t'No Category'  
%b= @dish.name
%p= @dish.recipe

  
= link_to (t'Edit'), edit_admin_dish_path(@dish)
= link_to (t'Back'), admin_dishes_path

app/views/admin/dishes/visibility.js.erb
$("#dishes_list").html("<%= escape_javascript( render 'dishes' ) %>");  
$.jGrowl("<%= escape_javascript(flash[:notice])%>");

app/views/admin/dishes/visibility.js.haml
-# проверка
-# #{"alert('hello');"}

-# $("#flash_notice").html("#{escape_javascript(flash[:notice])}");
$("#dishes_list").html("#{escape_javascript(render :partial => "/admin/shared/dishes_list", :locals => { :dishes => @dishes })}");

app/views/admin/main/index.html.erb
<h1>Admin::Main#index</h1>
<p>Find me in app/views/admin/main/index.html.erb</p>

app/views/admin/main/index.html.haml
Admin Main Index

app/views/admin/shared/_categories_list.html.haml
%h2=t'Categories'
#categories
  - unless categories.blank?
    %table
      - categories.each do |category|
        %tr
          %td
            - link_to admin_category_path(category) do
              = category.name
              (#{category.dishes.count})          
          %td        
            = link_to (t'Edit'), edit_admin_category_path(category)
            = link_to (t'Destroy'), [:admin, category], :confirm => "#{t'Are you sure?'}", :method => :delete
  - else 
    %p=t'Oops, No Categories' 
  
%br= link_to (t'New Category'), new_admin_category_path         

app/views/admin/shared/_categories_list_OLD.html.haml
%h2=t'Categories'
#categories
  - unless categories.blank?
    %table
      - categories.each do |category|
        %tr
          %td
            - link_to admin_category_path(category) do
              = category.name
              (#{category.dishes.count})          
          %td        
            = link_to (t'Edit'), edit_admin_category_path(category)
            = link_to (t'Destroy'), [:admin, category], :confirm => "#{t'Are you sure?'}", :method => :delete
  - else 
    %p=t'Oops, No Categories' 
  
%br= link_to (t'New Category'), new_admin_category_path         

app/views/admin/shared/_dishes_list.html.haml
#dishes_list
  - unless dishes.blank?
    %table
      %thead
        %tr.pretty
          %th= sortable "id"
          %th= sortable "name", "#{t'activerecord.attributes.dish.name'}"        
          %th= t'activerecord.attributes.dish.category'
          %th= sortable "created_at", "#{t'activerecord.attributes.dish.created_at'}"    
          %th= sortable "visible", "#{t'activerecord.attributes.dish.visible'}"
          %th=t'Operations'
      %tbody       
        - dishes.each do |dish|
          %tr
            %td= dish.id
            %td= link_to dish.name,  [:admin, dish]
            %td
              - unless dish.category.blank? 
                = dish.category.name 
              - else 
                .lack=t'No Category'                  
            %td= l(dish.created_at, :format => :long_date)
            %td= dish.visible ? 'yes': "#{t'Deleted'}"      
            
            %td          
              - if dish.visible
                = link_to (t'Delete'), visibility_admin_dish_path(dish), :confirm => "#{t'Are you sure?'}", :remote => true        
              - else            
                = link_to (t'Restore'), visibility_admin_dish_path(dish), :confirm => "#{t'Are you sure?'}", :remote => true  
                            
              = link_to (t'Edit'), edit_admin_dish_path(dish)                 
              = link_to (t'Destroy'), [:admin, dish], :confirm => "#{t'Are you sure?'}", :method => :delete#, :remote => true
              
  - else 
    %p=t'Oops, No Dishes'

app/views/admin/shared/_dishes_list_OLD.html.haml
#dishes_list
  - unless dishes.blank?
    %table.diches_table
      %tr.pretty
        %th= sortable "id"
        %th= sortable "name", "#{t'activerecord.attributes.dish.name'}"        
        %th= t'activerecord.attributes.dish.category'
        %th= sortable "created_at", "#{t'activerecord.attributes.dish.created_at'}"    
        %th= sortable "visible", "#{t'activerecord.attributes.dish.visible'}"
        %th=t'Operations'       
      - dishes.each do |dish|
        %tr
          %td= dish.id
          %td= link_to dish.name,  [:admin, dish]
          %td
            - unless dish.category.blank? 
              = link_to dish.category.name, admin_category_path(dish.category) 
            - else 
              .lack=t'No Category'                  
          %td= l(dish.created_at, :format => :long_date)
          %td= dish.visible ? 'yes': "#{t'Deleted'}"      
          
          %td          
            - if dish.visible
              = link_to (t'Delete'), visibility_admin_dish_path(dish), :confirm => "#{t'Are you sure?'}", :remote => true        
            - else            
              = link_to (t'Restore'), visibility_admin_dish_path(dish), :confirm => "#{t'Are you sure?'}", :remote => true  
                          
            = link_to (t'Edit'), edit_admin_dish_path(dish)                 
            = link_to (t'Destroy'), [:admin, dish], :confirm => "#{t'Are you sure?'}", :method => :delete#, :remote => true
            
  - else 
    %p=t'Oops, No Dishes'

app/views/layouts/admin.html.haml
!!!
%html
%head
  %title=title  
  = stylesheet_link_tag 'formtastic', 'formtastic_changes'
  = stylesheet_link_tag 'blueprint/screen', :media => 'screen'
  = stylesheet_link_tag 'blueprint/print',  :media => 'print'
  = stylesheet_link_tag 'admin/admin'  
  <!--[if lt IE]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->  
      
  = javascript_include_tag :defaults
  = csrf_meta_tag
  
%body
  .container
    -# .showgrid  
    #header.box
      %h1= link_to (t'Cookbook'), admin_root_path
      
      .flashes
        = content_tag :p, flash[:success], :id => 'flash_notice', :class => 'success' if flash[:success]
        = content_tag :p, flash[:notice], :id => 'flash_notice', :class => 'notice' if flash[:notice]
        = content_tag :p, flash[:warning], :id => 'flash_warning', :class => 'warning' if flash[:warning]
        = content_tag :p, flash[:error], :id => 'flash_error', :class => 'error' if flash[:error]
        
        -# = content_tag :p, flash[:notice], :id => 'flash_notice', :class => 'notice' if flash[:notice]
        -# #flash_notice.notice

      #nav
        %ul
          %li= link_to (t'Categories'), admin_categories_path
          %li= link_to (t'Dishes'), admin_dishes_path
        
    #section
      = yield
      
    #footer
      %hr
      .center
        I &hearts; my wife 
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/public.html.haml
!!!
%html
  %head
    %title=title
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
      
    = stylesheet_link_tag 'public'
       
  %body
    #page     
      #content
        #header
          %h1=link_to (t'Cookbook'), root_path
                    
        #about
          %h3
            CookBook
          = link_to (t'About'), about_path
            
        #getting-started
          
          = yield        
          
      #footer 
        I &hearts; my wife 
        

app/views/main/about.html.haml
About Page

app/views/main/index.html.haml
Public! Hello!
Home page